### ISSUE TITLE
Stuck at "Building the file tree"

### ISSUE THREAD

**Issue by lostcoda** [zuqq/surge#1]
Tried downloading a file couple of times and it gets stuck at building the file tree

```
➜ python -m surge --file archlinux-2019.12.01-x86_64.iso.torrent
Using metadata file archlinux-2019.12.01-x86_64.iso.torrent.
Building the file tree...Done.
```

And it stays that way indefinitely.

**Comment by zuqq** [comment]
Looking at the logs (there's a `--log` switch), this seems to be a problem with supplied tracker: requesting peers from the tracker fails with `"torrent not found"`. I get the same error when using transmission.

**Comment by zuqq** [comment]
Starting with 5f36b7c1911deb62b7d2447054d77c04a9b6ba0b, the command line interface displays the number of trackers that could be reached.
